"""Generate the DigitalSecretary Requirements + Traceability Matrix spreadsheets.

Outputs (single source of truth = this script's data tables):
  docs/requirements/DigitalSecretary-Requirements.xlsx      (flat list, JIRA-importable)
  docs/traceability/DigitalSecretary-Traceability-Matrix.xlsx (bi-directional artifact map)

Run:  python tools/docgen/build_excel_docs.py
"""
from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.formatting.rule import FormulaRule
from openpyxl.utils import get_column_letter
from openpyxl.comments import Comment

BANNER = ("AUTO-GENERATED by tools/docgen/build_excel_docs.py - do NOT edit this workbook by hand. "
          "Edit the script's data tables and run: python tools/docgen/build_excel_docs.py")
BANNER_FONT = Font(name="Arial", bold=True, color="C00000", size=10)

ROOT = Path(__file__).resolve().parents[2]
FONT = "Arial"
HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
HEADER_FONT = Font(name=FONT, bold=True, color="FFFFFF", size=10)
BODY_FONT = Font(name=FONT, size=10)
WRAP_TOP = Alignment(wrap_text=True, vertical="top")
THIN = Side(style="thin", color="D9D9D9")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

# --------------------------------------------------------------------------- #
# 1. REQUIREMENTS  (Req ID, Issue Type, Feature/Epic, Sub-feature, Priority,
#    Status, Summary, Description, User Story, Acceptance Criteria, Doc)
# --------------------------------------------------------------------------- #
REQ_HEADERS = ["Req ID", "Issue Type", "Feature (Epic)", "Sub-feature", "Priority",
               "Status", "Summary", "Description", "User Story",
               "Acceptance Criteria", "Requirement Doc"]

APP = "Application Shell"
NFR = "Non-Functional"
LAU, CAL, CLP, EML = "Launcher", "Calculator", "Clipboard History", "Download Emails"
GML, GDR = "Download Gmail", "Download Google Drive"
EIN = "Email Intelligence"
RD = "docs/requirements/REQUIREMENTS.md"
RDF = "docs/requirements/features/{}.md"

REQUIREMENTS = [
    ("APP-1", "Story", APP, "Plugin discovery", "High", "Done",
     "Discover features from manifests",
     "App discovers installed features from the plugins folder using plugin.json; no feature code loaded at startup.",
     "As a user, I want the app to find its tools automatically.", "Manifests are read; no feature DLL loads at startup.", RD),
    ("APP-2", "Story", APP, "Lazy loading", "High", "Done",
     "Load a feature only when opened",
     "A feature's code is loaded only when first opened, then reused.",
     "As a user, I want the app to start fast.", "Feature DLL loads on first open and is cached.", RD),
    ("APP-3", "Story", APP, "Menu navigation", "High", "Done",
     "Menu grouped Category > Feature",
     "Features are reachable via a menu grouped as Category then Feature.",
     "As a user, I want to open any tool from the menu.", "Every visible feature appears under its category.", RD),
    ("APP-4", "Story", APP, "Dashboard", "Medium", "Done",
     "Home dashboard of feature tiles",
     "A Home dashboard shows a tile per visible feature; clicking a tile opens it.",
     "As a user, I want a home screen of my tools.", "Visible features render as tiles; click opens the feature.", RD),
    ("APP-5", "Story", APP, "Configure Features", "High", "Done",
     "Show/hide per dashboard and menu",
     "A Configure Features dialog lets the user show/hide each feature on the dashboard and in the menu independently; choices persist.",
     "As a user, I want to choose what I see, where.", "Toggles persist; menu and dashboard update immediately.", RD),
    ("APP-6", "Story", APP, "Data isolation", "High", "Done",
     "Each feature owns its data folder",
     "Each feature stores data in its own private folder; features never read/write each other's data.",
     "As a user, I want my tools' data kept separate.", "Each feature writes only under its own data directory.", RD),
    ("APP-7", "Story", APP, "Extensibility", "High", "Done",
     "Add a feature without changing the host",
     "A new feature can be added without modifying the host.",
     "As a builder, I want to add features as plugins.", "Adding a feature requires no host change.", RD),
    ("APP-8", "Story", APP, "Fault isolation", "High", "Done",
     "A failing feature must not crash the app",
     "A failing feature must not crash the host; the user sees a clear error.",
     "As a user, I want the app to survive a broken tool.", "A feature error is contained and reported; host stays alive.", RD),

    ("NFR-1", "NFR", NFR, "Performance", "High", "Done", "Fast startup / instant open",
     "Startup loads only manifests; opening a feature is near-instant.", "", "Startup loads no feature code.", RD),
    ("NFR-2", "NFR", NFR, "Privacy/Security", "High", "Done", "Secrets never persisted; data local",
     "Secrets (e.g. email app password) are never persisted; all data is local to the PC.", "", "No password written to disk; no network upload of data.", RD),
    ("NFR-3", "NFR", NFR, "Reliability", "High", "Done", "Errors contained, reported",
     "A feature error is contained and reported; the host stays alive.", "", "Per-item failures are logged; processing continues.", RD),
    ("NFR-4", "NFR", NFR, "Usability", "Medium", "Done", "Consistent, discoverable UI",
     "Consistent layout; features discoverable via menu and dashboard.", "", "Menu + dashboard expose every visible feature.", RD),
    ("NFR-5", "NFR", NFR, "Quality", "High", "Done", "Tested + analyzed + covered",
     "Logic unit-tested; plugin pipeline QA-tested; static analysis clean; coverage on target.", "", "build.ps1 -All = PASS; coverage >= target.", RD),
    ("NFR-6", "NFR", NFR, "Extensibility", "High", "Done", "Plugin architecture",
     "Features are independent projects loaded as plugins.", "", "Host references no feature.", RD),
    ("NFR-7", "NFR", NFR, "Portability", "Medium", "Done", "Windows 10/11, .NET 9",
     "Runs on Windows 10/11 with the .NET 9 runtime.", "", "App launches on a clean Win10/11 + .NET 9 machine.", RD),

    ("LAU-1", "Story", LAU, "Add shortcut", "High", "Done", "Add app/file/folder/URL shortcut",
     "The user can add a shortcut to an application/file, a folder, or a URL.",
     "As a user, I want to save a shortcut so I can reach it quickly.", "Each add flow creates a named item with a target.", RDF.format("launcher")),
    ("LAU-2", "Story", LAU, "Shortcut model", "Low", "Done", "Name + Target per shortcut",
     "Each shortcut has a friendly Name and a Target (path or URL).", "", "Items show Name and Target columns.", RDF.format("launcher")),
    ("LAU-3", "Story", LAU, "Launch", "High", "Done", "Open with default handler",
     "Double-click or Launch opens the target with its default Windows handler.",
     "As a user, I want one-click open.", "Apps/files/folders/URLs all open correctly.", RDF.format("launcher")),
    ("LAU-4", "Story", LAU, "Edit", "Medium", "Done", "Edit name/target",
     "The user can edit a shortcut's name and target.", "", "Changes persist and show in the list.", RDF.format("launcher")),
    ("LAU-5", "Story", LAU, "Remove", "Medium", "Done", "Remove with confirm",
     "The user can remove a shortcut (with confirmation).", "", "Item disappears and stays gone after restart.", RDF.format("launcher")),
    ("LAU-6", "Story", LAU, "Persistence", "High", "Done", "Persist locally; reload",
     "Shortcuts persist locally and reload on next launch.", "", "List survives restart; corrupt file => empty list, no crash.", RDF.format("launcher")),
    ("LAU-7", "Story", LAU, "Launch failure", "Medium", "Done", "Failed launch reported, no crash",
     "A failed launch shows a clear message and does not crash the app.", "", "Bad target shows a warning; app keeps running.", RDF.format("launcher")),

    ("CAL-1", "Story", CAL, "Display", "Medium", "Done", "Show expression/result",
     "A display shows the current expression/result.", "", "Display reflects keypad/typed input.", RDF.format("calculator")),
    ("CAL-2", "Story", CAL, "Keypad", "Medium", "Done", "Digits, operators, parentheses",
     "A keypad provides digits, '.', + - x /, parentheses, C, backspace, =.", "", "Each key acts as labelled.", RDF.format("calculator")),
    ("CAL-3", "Story", CAL, "Typed expression", "Medium", "Done", "Type + Enter to evaluate",
     "The user can type directly and press Enter to evaluate.", "", "(12+5)*2 = 34.", RDF.format("calculator")),
    ("CAL-4", "Story", CAL, "Operators", "Medium", "Done", "+ - x / and parentheses",
     "Supports + - x / and parentheses; display operators map to ASCII internally.", "", "2x3=6; 6/2=3; 9-4=5.", RDF.format("calculator")),
    ("CAL-5", "Story", CAL, "Error handling", "Medium", "Done", "Invalid -> Error; /0 -> Error",
     "Invalid input shows 'Error' (no crash). Division by zero is treated as an error.", "", "2+ => Error; abc => Error; 5/0 => Error.", RDF.format("calculator")),

    ("CLP-1", "Story", CLP, "Auto-capture", "High", "Done", "Capture copied text",
     "While open, new clipboard text is captured automatically.", "", "Copying new text adds it to the top.", RDF.format("clipboard-history")),
    ("CLP-2", "Story", CLP, "List", "Medium", "Done", "Newest-first, deduped, max 50",
     "Entries are listed newest-first, de-duplicated, capped at 50; each shows a single-line preview.", "", "Preview collapses newlines and truncates long text.", RDF.format("clipboard-history")),
    ("CLP-3", "Story", CLP, "Re-copy", "High", "Done", "Copy entry back",
     "The user can copy a selected entry back to the clipboard (double-click or Copy).", "", "Selected full text goes to the clipboard.", RDF.format("clipboard-history")),
    ("CLP-4", "Story", CLP, "Delete/Clear", "Low", "Done", "Delete one / clear all",
     "The user can delete a selected entry or clear all.", "", "Delete removes one; clear empties the list.", RDF.format("clipboard-history")),
    ("CLP-5", "Story", CLP, "Resilience", "Medium", "Done", "Clipboard errors ignored",
     "Clipboard read/write errors are ignored gracefully (no crash).", "", "A locked clipboard does not crash the feature.", RDF.format("clipboard-history")),

    ("EML-1", "Story", EML, "Connect & auth", "High", "Done", "IMAP SSL + app password",
     "Connect to Yahoo over IMAP (SSL) using the user's email + app password.", "", "Normal password => clear app-password message.", RDF.format("email-downloader")),
    ("EML-2", "Story", EML, "Folder traversal", "High", "Done", "Visit all folders",
     "Traverse all folders (Inbox, Sent, Archive, Spam, custom, nested).", "", "Every selectable folder is visited; counts shown.", RDF.format("email-downloader")),
    ("EML-3", "Story", EML, "Read-only copy", "High", "Done", "Nothing changed on server",
     "Open folders read-only so nothing is deleted, moved, or marked read on the server.", "", "Mailbox unchanged after a run.", RDF.format("email-downloader")),
    ("EML-4", "Story", EML, "Save .txt + .eml", "High", "Done", "Both formats per email",
     "Save each email as both .txt (readable) and .eml (full fidelity).", "", "Each message yields a date-prefixed .txt and .eml.", RDF.format("email-downloader")),
    ("EML-5", "Story", EML, "Attachments", "High", "Done", "All attachments incl. inline",
     "Save all attachments as-is, including inline/embedded images.", "", "File attachments keep names; inline parts get synthesised names.", RDF.format("email-downloader")),
    ("EML-6", "Story", EML, "Mirror + collisions", "Medium", "Done", "Mirror folders; _1,_2 on clash",
     "Mirror the remote folder structure locally; resolve name collisions with _1, _2, ...", "", "Folder tree recreated; no overwrite on collision.", RDF.format("email-downloader")),
    ("EML-7", "Story", EML, "Progress & cancel", "Medium", "Done", "Progress bar + log + cancel",
     "Show a progress bar + log; allow Cancel; report per-item errors and continue.", "", "Bar advances; Cancel stops cleanly.", RDF.format("email-downloader")),
    ("EML-8", "Story", EML, "Remember, no password", "High", "Done", "Remember email/folder; never store password",
     "Remember the email address + target folder; never store the password.", "", "Settings file has email + folder only.", RDF.format("email-downloader")),

    ("GML-1", "Story", GML, "Connect & auth", "High", "Done", "IMAP SSL + app password",
     "Connect to Gmail over IMAP (SSL) using the user's email + app password.", "", "Normal password => clear app-password message.", RDF.format("gmail-downloader")),
    ("GML-2", "Story", GML, "Folder/label traversal", "High", "Done", "Visit all folders/labels",
     "Traverse all folders/labels (Inbox, Sent, [Gmail]/All Mail, custom, nested).", "", "Every selectable folder is visited; counts shown.", RDF.format("gmail-downloader")),
    ("GML-3", "Story", GML, "Read-only copy", "High", "Done", "Nothing changed on server",
     "Open folders read-only so nothing is deleted, moved, or marked read on the server.", "", "Mailbox unchanged after a run.", RDF.format("gmail-downloader")),
    ("GML-4", "Story", GML, "Save .txt + .eml", "High", "Done", "Both formats per email",
     "Save each email as both .txt (readable) and .eml (full fidelity).", "", "Each message yields a date-prefixed .txt and .eml.", RDF.format("gmail-downloader")),
    ("GML-5", "Story", GML, "Attachments", "High", "Done", "All attachments incl. inline",
     "Save all attachments as-is, including inline/embedded images.", "", "File attachments keep names; inline parts get synthesised names.", RDF.format("gmail-downloader")),
    ("GML-6", "Story", GML, "Mirror + collisions", "Medium", "Done", "Mirror folders; _1,_2 on clash",
     "Mirror the remote folder structure locally; resolve name collisions with _1, _2, ...", "", "Folder tree recreated; no overwrite on collision.", RDF.format("gmail-downloader")),
    ("GML-7", "Story", GML, "Progress & cancel", "Medium", "Done", "Progress bar + log + cancel",
     "Show a progress bar + log; allow Cancel; report per-item errors and continue.", "", "Bar advances; Cancel stops cleanly.", RDF.format("gmail-downloader")),
    ("GML-8", "Story", GML, "Remember, no password", "High", "Done", "Remember email/folder; never store password",
     "Remember the email address + target folder; never store the password.", "", "Settings file has email + folder only.", RDF.format("gmail-downloader")),

    ("GDR-1", "Story", GDR, "OAuth sign-in", "High", "Done", "OAuth read-only + token cache",
     "Authenticate with the OAuth installed-app flow using the user's Desktop-app client; read-only Drive scope; cache the token.", "", "Missing creds => clear setup message; first run consents in browser.", RDF.format("google-drive-downloader")),
    ("GDR-2", "Story", GDR, "List & tree", "High", "Done", "List files; build folder tree",
     "List all non-trashed files via the Drive API (paged) and build the folder tree from parents.", "", "All items listed; parent chain resolves to a path.", RDF.format("google-drive-downloader")),
    ("GDR-3", "Story", GDR, "Mirror structure", "Medium", "Done", "Recreate Drive tree locally",
     "Mirror the Drive folder structure on disk.", "", "Local folders match the Drive tree.", RDF.format("google-drive-downloader")),
    ("GDR-4", "Story", GDR, "Download files", "High", "Done", "Regular files as-is",
     "Download regular files (PDF, images, Office, ...) as-is.", "", "Binary files saved byte-for-byte with original names.", RDF.format("google-drive-downloader")),
    ("GDR-5", "Story", GDR, "Export Google docs", "High", "Done", "Docs -> Office + PDF",
     "Export Google-native files to both an Office format and PDF (Docs->docx, Sheets->xlsx, Slides->pptx, Drawings->png; all +pdf).", "", "A Doc yields .docx + .pdf; a Sheet .xlsx + .pdf.", RDF.format("google-drive-downloader")),
    ("GDR-6", "Story", GDR, "Skip + collisions", "Medium", "Done", "Skip non-exportable; _1,_2 on clash",
     "Skip non-exportable native items with a note; resolve name collisions with _1, _2, ...", "", "Forms/Sites skipped with a note; no overwrite on collision.", RDF.format("google-drive-downloader")),
    ("GDR-7", "Story", GDR, "Progress & cancel", "Medium", "Done", "Progress bar + log + cancel",
     "Show a progress bar + log; allow Cancel; report per-item errors and continue.", "", "Bar advances; Cancel stops cleanly.", RDF.format("google-drive-downloader")),
    ("GDR-8", "Story", GDR, "Remember, token cached", "High", "Done", "Remember path/folder; token cached separately",
     "Remember the credentials-file path + target folder; cache the OAuth token separately, never in settings.", "", "Settings file has path + folder only; token under token/.", RDF.format("google-drive-downloader")),

    # Email Intelligence (offline analysis of the downloaded archive)
    ("EI-A1", "Story", EIN, "Scan archive", "High", "Done", "Discover .eml/.txt files",
     "Recursively find .eml and .txt files in the chosen archive folder.", "", "Files under the folder are found; .eml preferred over its .txt sibling.", RDF.format("email-intelligence")),
    ("EI-A2", "Story", EIN, "Parse .eml", "High", "Done", "Parse MIME via MimeKit",
     "Parse .eml headers, body and attachments with MimeKit.", "", "From/To/Cc/Subject/Date/Message-Id and body are extracted.", RDF.format("email-intelligence")),
    ("EI-A3", "Story", EIN, "Parse .txt", "Medium", "Done", "Parse the readable .txt form",
     "Parse the .txt form written by the downloaders (header lines, separator, body).", "", "From/To/Date/Subject and body are read from a .txt file.", RDF.format("email-intelligence")),
    ("EI-A4", "Story", EIN, "Decode & clean", "High", "Done", "Decode encodings; HTML to text",
     "Decode MIME/encodings and convert HTML bodies to clean text; no mojibake.", "", "An HTML body renders as readable text; whitespace normalized.", RDF.format("email-intelligence")),
    ("EI-B1", "Story", EIN, "Dedupe by Message-Id", "High", "Done", "Remove exact duplicates",
     "Remove exact duplicate messages by Message-Id.", "", "Two messages with the same Message-Id collapse to one.", RDF.format("email-intelligence")),
    ("EI-B2", "Story", EIN, "Dedupe by content", "High", "Done", "Collapse cross-account copies",
     "Remove near-duplicates by a content hash when Message-Id is absent.", "", "Identical mail with no Message-Id collapses to one.", RDF.format("email-intelligence")),
    ("EI-B3", "Story", EIN, "Thread key", "Medium", "Done", "Group into conversations",
     "Compute a thread key from references or normalized subject.", "", "Re:/Fwd: subjects map to the same thread key.", RDF.format("email-intelligence")),
    ("EI-B4", "Story", EIN, "Classify", "Medium", "Done", "Personal/Newsletter/Txn/Notification",
     "Classify each message using local sender/subject heuristics.", "", "noreply senders are bulk; receipts transactional; verify is notification.", RDF.format("email-intelligence")),
    ("EI-C1", "Story", EIN, "Extract participants", "High", "Done", "Every address + name",
     "Extract every participant (address + display name) across From/To/Cc.", "", "All participants are captured with their display names.", RDF.format("email-intelligence")),
    ("EI-C2", "Story", EIN, "Detect owner", "High", "Done", "Identify the archive owner",
     "Detect the owner from the most frequent sender; override allowed.", "", "The most frequent From address is treated as the owner.", RDF.format("email-intelligence")),
    ("EI-C3", "Story", EIN, "Identity resolution", "High", "Done", "Merge a person's addresses",
     "Merge addresses that share a normalized full name into one person.", "", "Two addresses with the same full name become one person.", RDF.format("email-intelligence")),
    ("EI-C4", "Story", EIN, "Person record", "Medium", "Done", "Canonical person model",
     "Build a Person with canonical name, addresses and name variants.", "", "Each person lists all of their addresses.", RDF.format("email-intelligence")),
    ("EI-C5", "Story", EIN, "Signature details", "Medium", "Done", "Phones + links from signatures",
     "Extract phone numbers and web/social links from message bodies.", "", "A signature's phone and URL are captured.", RDF.format("email-intelligence")),
    ("EI-C6", "Story", EIN, "Contact export", "High", "Done", "vCard + CSV export",
     "Export the contact list as vCard and CSV for re-import.", "", "A valid .vcf and a CSV with all contacts are written.", RDF.format("email-intelligence")),
    ("EI-D1", "Story", EIN, "Relationship metrics", "High", "Done", "Counts, first/last contact",
     "Compute per-person sent/received counts and first/last contact.", "", "Direction counts and dates match the messages.", RDF.format("email-intelligence")),
    ("EI-D2", "Story", EIN, "Strength score", "Medium", "Done", "Volume+reciprocity+recency",
     "Compute a transparent relationship strength score (0-100).", "", "More frequent, recent, two-way contacts score higher.", RDF.format("email-intelligence")),
    ("EI-D3", "Story", EIN, "Dormant flag", "Medium", "Done", "Flag lapsed contacts",
     "Flag historically frequent contacts with no recent contact.", "", "A long-silent frequent contact is flagged dormant.", RDF.format("email-intelligence")),
    ("EI-D4", "Story", EIN, "Co-occurrence edges", "Medium", "Done", "Who appears together",
     "Build weighted co-occurrence edges between people on shared emails.", "", "People on the same email are linked, weighted by frequency.", RDF.format("email-intelligence")),
    ("EI-D5", "Story", EIN, "Organization", "Low", "Done", "Org from email domain",
     "Derive an organization name from a non-free-mail email domain.", "", "Company domains yield an org; free-mail yields none.", RDF.format("email-intelligence")),
    ("EI-E1", "Story", EIN, "Topics", "Medium", "Done", "Keyword extraction",
     "Extract per-person and global topics by local word frequency.", "", "Frequent non-stopwords surface as topics.", RDF.format("email-intelligence")),
    ("EI-E2", "Story", EIN, "Tone & sentiment", "Medium", "Done", "Lexicon tone (no AI)",
     "Score relationship tone with a bundled offline lexicon; label Positive/Neutral/Negative.", "", "Warm messages score positive; complaints negative; heuristic labelled.", RDF.format("email-intelligence")),
    ("EI-F1", "Story", EIN, "Purchases / receipts", "Medium", "Done", "Extract orders + amounts",
     "Detect purchase/receipt/order emails and capture amount + currency.", "", "A receipt email yields a Purchase item with its amount.", RDF.format("email-intelligence")),
    ("EI-F2", "Story", EIN, "Subscriptions", "Medium", "Done", "Detect recurring/renewals",
     "Detect subscription/renewal/recurring emails.", "", "A renewal email is categorized as Subscription.", RDF.format("email-intelligence")),
    ("EI-F3", "Story", EIN, "Travel", "Medium", "Done", "Detect trips/bookings",
     "Detect flight/hotel/booking-confirmation emails.", "", "A flight confirmation is categorized as Travel.", RDF.format("email-intelligence")),
    ("EI-F4", "Story", EIN, "Account inventory", "Medium", "Done", "Services signed up for",
     "Detect welcome/verify/reset emails to inventory account sign-ups.", "", "A welcome/verify email is categorized as Account.", RDF.format("email-intelligence")),
    ("EI-F7", "Story", EIN, "Document library", "Medium", "Done", "Deduped attachment library",
     "Collect attachments into a hash-deduped, type-classified document library.", "", "Identical attachments are counted once; each is typed (PDF/Image/...).", RDF.format("email-intelligence")),
    ("EI-G1", "Story", EIN, "People search", "High", "Done", "Type-ahead search",
     "Search people by name or email in the report.", "", "Typing filters the people list live.", RDF.format("email-intelligence")),
    ("EI-G2", "Story", EIN, "Dossier", "High", "Done", "Per-person detail card",
     "Show a dossier with details, metrics and topics for a person.", "", "Selecting a person shows their full dossier.", RDF.format("email-intelligence")),
    ("EI-G4", "Story", EIN, "Drill-through", "Medium", "Done", "Open original message",
     "Link timeline entries to their source message file.", "", "Each timeline entry links to its .eml/.txt source.", RDF.format("email-intelligence")),
    ("EI-G6", "Story", EIN, "Timeline", "High", "Done", "Relationship history timeline",
     "Build an ordered per-person interaction timeline.", "", "A person's interactions appear in date order with direction.", RDF.format("email-intelligence")),
    ("EI-H1", "Story", EIN, "Tabular output", "High", "Done", "Excel-ready CSV sheets",
     "Write contacts/relationships as CSV (opens in Excel).", "", "A Contacts.csv with a header and one row per person is written.", RDF.format("email-intelligence")),
    ("EI-H2", "Story", EIN, "Portable formats", "Medium", "Done", "JSON/vCard/GraphML",
     "Write JSON, vCard and GraphML companion outputs.", "", "report.json, Contacts.vcf and network.graphml are written.", RDF.format("email-intelligence")),
    ("EI-H5", "Story", EIN, "No database", "High", "Done", "Files only; offline",
     "Write all outputs as files under the output folder; no database.", "", "Output folder contains files only; no DB; no network used.", RDF.format("email-intelligence")),
    ("EI-I1", "Story", EIN, "Idempotent re-run", "Medium", "Done", "Re-run without duplicating",
     "Re-running on the same archive does not double-count (dedupe).", "", "A second run yields the same counts.", RDF.format("email-intelligence")),
    ("EI-I4", "Story", EIN, "Append / overwrite", "High", "Done", "Consolidate archives or replace",
     "Append merges a new archive with the persisted prior messages and re-dedupes; overwrite uses the current input only.", "", "Append across two archives yields one deduped dataset; overwrite replaces.", RDF.format("email-intelligence")),
    ("EI-J1", "Story", EIN, "Configuration", "Medium", "Done", "Folders + owner option",
     "Configure input/output folders and an optional owner address.", "", "Chosen folders and owner are used by the run.", RDF.format("email-intelligence")),
    ("EI-J2", "Story", EIN, "Progress & cancel UI", "Medium", "Done", "Bar + log + cancel",
     "Run on a background worker with a progress bar, log and cancel.", "", "The bar advances; Cancel stops cleanly.", RDF.format("email-intelligence")),
    ("EI-J3", "Story", EIN, "Settings storage", "Medium", "Done", "Persist; no secrets",
     "Persist settings under the feature data folder; store no secrets.", "", "Settings file holds folders + owner only.", RDF.format("email-intelligence")),
    ("EI-J4", "Story", EIN, "Open report", "Low", "Done", "Open the HTML report",
     "Offer to open the generated HTML report after a run.", "", "Open report launches index.html in the browser.", RDF.format("email-intelligence")),
    ("EI-J5", "Story", EIN, "Phased progress", "Medium", "Done", "Per-phase progress + detail",
     "Report progress per phase with percent and current detail.", "", "Each phase reports a percent and a detail line.", RDF.format("email-intelligence")),
    ("EI-K1", "Story", EIN, "HTML report tabs", "High", "Done", "Tabbed HTML5 report",
     "Generate a single HTML report with tabbed views.", "", "index.html opens with Overview/People/Timeline/Graph/Topics tabs.", RDF.format("email-intelligence")),
    ("EI-K2", "Story", EIN, "Folder data store", "Medium", "Done", "Data beside the report",
     "Store the report's data in a data/ folder beside index.html.", "", "data/data.js holds the model the page reads.", RDF.format("email-intelligence")),
    ("EI-K3", "Story", EIN, "Offline report", "High", "Done", "No CDN; opens from file://",
     "The report is fully offline; data loads via a script tag.", "", "Opening index.html from disk works with no network.", RDF.format("email-intelligence")),
    ("EI-K4", "Story", EIN, "Client-side nav", "Medium", "Done", "Search + tabs, no reload",
     "Navigate and search client-side without reloading.", "", "Switching tabs and searching update without a reload.", RDF.format("email-intelligence")),
]

# --------------------------------------------------------------------------- #
# 2. TRACEABILITY MATRIX
#    Feature, Sub-feature, Req IDs, Req Doc, Mock/Screen, Code, Unit Test,
#    QA, User Manual, Architecture Doc, Code Doc, [Coverage formula], Notes
# --------------------------------------------------------------------------- #
TRACE_HEADERS = ["Feature", "Sub-feature", "Requirement ID(s)", "Requirement Doc",
                 "Mock / Screen", "Code Reference", "Unit Test Reference",
                 "QA Automation Reference", "User Manual Ref", "Architecture Doc",
                 "Code Doc (FEATURE.md)", "Coverage", "Notes"]

QA = "tests/DigitalSecretary.QaTests/PluginPipelineQaTests.cs"
QA_LOAD = QA + " (Feature_loads_instantiates_and_builds_a_view)"
QA_MAIL = QA + " (Email_feature_resolves_its_own_private_MailKit)"
QA_GMAIL = QA + " (Gmail_feature_resolves_its_own_private_MailKit)"
QA_DRIVE = QA + " (Drive_feature_resolves_its_own_private_Google_Apis)"
ARCH = "docs/ARCHITECTURE.md"
MAN = "docs/user-guide/DigitalSecretary-User-Manual.html"
IMG = "docs/user-guide/images/{}.png"
FDOC = "src/Features/{}/FEATURE.md"
UG_EI = "docs/user-guide/features/email-intelligence.md"
UT_EI = "tests/DigitalSecretary.UnitTests/Features/EmailIntelligence/"
UI_QA = "n/a (UI - covered by QA automation)"
NET_QA = "n/a (network - covered by QA + manual run)"

TRACE = [
    # Application shell
    (APP, "Plugin discovery & lazy loading", "APP-1, APP-2", RD, "-",
     "src/DigitalSecretary.App/Hosting/ (PluginCatalog, PluginLoadContext, PluginLoader, LoadedFeature)",
     "tests/DigitalSecretary.UnitTests/App/PluginCatalogTests.cs", QA_LOAD,
     MAN + "#start", ARCH + " (#lifecycle)", ARCH, "Core plugin pipeline."),
    (APP, "Menu & dashboard navigation", "APP-3, APP-4", RD, IMG.format("main-shell"),
     "src/DigitalSecretary.App/MainForm.cs, src/DigitalSecretary.App/UI/DashboardControl.cs", UI_QA, QA_LOAD,
     MAN + "#window", ARCH, ARCH, "Menus + tiles built from manifests."),
    (APP, "Configure Features (show/hide)", "APP-5", RD, IMG.format("configure-features"),
     "src/DigitalSecretary.App/UI/ConfigureFeaturesForm.cs, src/DigitalSecretary.App/Settings/AppSettings.cs, src/DigitalSecretary.App/Settings/SettingsStore.cs",
     "tests/DigitalSecretary.UnitTests/App/HostTests.cs (Settings_round_trip_to_file)", QA_LOAD,
     MAN + "#configure", ARCH + " (#show-hide)", ARCH, "Dashboard + menu toggles persist."),
    (APP, "Per-feature data isolation", "APP-6", RD, "-",
     "src/DigitalSecretary.App/Hosting/FeatureContext.cs",
     "tests/DigitalSecretary.UnitTests/App/HostTests.cs (FeatureContext_creates_and_exposes_private_data_dir)",
     QA_LOAD, MAN + "#data", ARCH + " (#per-feature-data)", ARCH, "Each feature gets its own data dir."),
    (APP, "Extensibility (add feature, no host change)", "APP-7", RD, "-",
     "src/Features/Directory.Build.props, src/DigitalSecretary.App/DigitalSecretary.App.csproj",
     "tests/DigitalSecretary.UnitTests/App/PluginCatalogTests.cs", QA_LOAD, MAN + "#window", ARCH, ARCH,
     "Host references Abstractions only; features auto-copied to plugins."),
    (APP, "Fault isolation (feature failure contained)", "APP-8", RD, "-",
     "src/DigitalSecretary.App/MainForm.cs", UI_QA, QA_LOAD, MAN + "#faq", ARCH, ARCH,
     "ActivateFeature wraps feature load in try/catch; host stays alive."),

    # Launcher
    (LAU, "Add app/file shortcut", "LAU-1", RDF.format("launcher"), IMG.format("launcher"),
     "src/Features/Launcher/LauncherControl.cs (AddFile)",
     "tests/DigitalSecretary.UnitTests/Features/StoreTests.cs", QA_LOAD, MAN + "#launcher", ARCH, FDOC.format("Launcher"), ""),
    (LAU, "Add folder shortcut", "LAU-1", RDF.format("launcher"), IMG.format("launcher"),
     "src/Features/Launcher/LauncherControl.cs (AddFolder)",
     "tests/DigitalSecretary.UnitTests/Features/StoreTests.cs", QA_LOAD, MAN + "#launcher", ARCH, FDOC.format("Launcher"), ""),
    (LAU, "Add URL shortcut", "LAU-1", RDF.format("launcher"), IMG.format("launcher"),
     "src/Features/Launcher/LauncherControl.cs (AddUrl)",
     "tests/DigitalSecretary.UnitTests/Features/StoreTests.cs", QA_LOAD, MAN + "#launcher", ARCH, FDOC.format("Launcher"), ""),
    (LAU, "Edit shortcut", "LAU-4", RDF.format("launcher"), IMG.format("launcher"),
     "src/Features/Launcher/LauncherControl.cs (EditSelected)",
     "tests/DigitalSecretary.UnitTests/Features/StoreTests.cs", QA_LOAD, MAN + "#launcher", ARCH, FDOC.format("Launcher"), ""),
    (LAU, "Remove shortcut", "LAU-5", RDF.format("launcher"), IMG.format("launcher"),
     "src/Features/Launcher/LauncherControl.cs (RemoveSelected)",
     "tests/DigitalSecretary.UnitTests/Features/StoreTests.cs", QA_LOAD, MAN + "#launcher", ARCH, FDOC.format("Launcher"), ""),
    (LAU, "Launch shortcut", "LAU-3, LAU-7", RDF.format("launcher"), IMG.format("launcher"),
     "src/Features/Launcher/LauncherControl.cs (LaunchSelected)", UI_QA, QA_LOAD, MAN + "#launcher", ARCH, FDOC.format("Launcher"), "ShellExecute; failures caught."),
    (LAU, "Persistence", "LAU-2, LAU-6", RDF.format("launcher"), IMG.format("launcher"),
     "src/Features/Launcher/LauncherStore.cs, src/Features/Launcher/LauncherItem.cs",
     "tests/DigitalSecretary.UnitTests/Features/StoreTests.cs (Launcher_round_trips_items, corrupt)", QA_LOAD, MAN + "#launcher", ARCH, FDOC.format("Launcher"), ""),

    # Calculator
    (CAL, "Keypad entry", "CAL-1, CAL-2", RDF.format("calculator"), IMG.format("calculator"),
     "src/Features/Calculator/CalculatorControl.cs (OnKey)",
     "tests/DigitalSecretary.UnitTests/Features/CalculatorEngineTests.cs", QA_LOAD, MAN + "#calculator", ARCH, FDOC.format("Calculator"), ""),
    (CAL, "Expression evaluation", "CAL-3, CAL-4", RDF.format("calculator"), IMG.format("calculator"),
     "src/Features/Calculator/CalculatorEngine.cs (Evaluate)",
     "tests/DigitalSecretary.UnitTests/Features/CalculatorEngineTests.cs", QA_LOAD, MAN + "#calculator", ARCH, FDOC.format("Calculator"), ""),
    (CAL, "Error handling", "CAL-5", RDF.format("calculator"), IMG.format("calculator"),
     "src/Features/Calculator/CalculatorEngine.cs (Evaluate)",
     "tests/DigitalSecretary.UnitTests/Features/CalculatorEngineTests.cs (Invalid_input_returns_error)", QA_LOAD, MAN + "#calculator", ARCH, FDOC.format("Calculator"), ""),

    # Clipboard
    (CLP, "Auto-capture + preview", "CLP-1, CLP-2", RDF.format("clipboard-history"), IMG.format("clipboard-history"),
     "src/Features/ClipboardHistory/ClipboardHistoryControl.cs (Poll), src/Features/ClipboardHistory/ClipboardPreview.cs",
     "tests/DigitalSecretary.UnitTests/Features/ClipboardPreviewTests.cs", QA_LOAD, MAN + "#clipboard", ARCH, FDOC.format("ClipboardHistory"), ""),
    (CLP, "Re-copy", "CLP-3", RDF.format("clipboard-history"), IMG.format("clipboard-history"),
     "src/Features/ClipboardHistory/ClipboardHistoryControl.cs (CopySelected)", UI_QA, QA_LOAD, MAN + "#clipboard", ARCH, FDOC.format("ClipboardHistory"), ""),
    (CLP, "Delete / Clear all", "CLP-4, CLP-5", RDF.format("clipboard-history"), IMG.format("clipboard-history"),
     "src/Features/ClipboardHistory/ClipboardHistoryControl.cs (DeleteSelected, ClearAll)", UI_QA, QA_LOAD, MAN + "#clipboard", ARCH, FDOC.format("ClipboardHistory"), ""),

    # Email
    (EML, "Connect & authenticate", "EML-1", RDF.format("email-downloader"), IMG.format("email-downloader"),
     "src/Features/EmailDownloader/EmailDownloader.cs (RunAsync)", NET_QA, QA_MAIL, MAN + "#email", ARCH, FDOC.format("EmailDownloader"), "App password required."),
    (EML, "Folder traversal (read-only)", "EML-2, EML-3", RDF.format("email-downloader"), IMG.format("email-downloader"),
     "src/Features/EmailDownloader/EmailDownloader.cs (CollectSelectableFoldersAsync)", NET_QA, QA_LOAD, MAN + "#email", ARCH, FDOC.format("EmailDownloader"), "EXAMINE / read-only."),
    (EML, "Save .txt + .eml + mirror", "EML-4, EML-6", RDF.format("email-downloader"), IMG.format("email-downloader"),
     "src/Features/EmailDownloader/EmailDownloader.cs (SaveMessage), src/Features/EmailDownloader/EmailFileNaming.cs",
     "tests/DigitalSecretary.UnitTests/Features/EmailFileNamingTests.cs", QA_LOAD, MAN + "#email", ARCH, FDOC.format("EmailDownloader"), ""),
    (EML, "Attachments (incl. inline)", "EML-5", RDF.format("email-downloader"), IMG.format("email-downloader"),
     "src/Features/EmailDownloader/AttachmentScanner.cs",
     "tests/DigitalSecretary.UnitTests/Features/AttachmentScannerTests.cs", QA_LOAD, MAN + "#email", ARCH, FDOC.format("EmailDownloader"), ""),
    (EML, "Progress & cancel + errors", "EML-7", RDF.format("email-downloader"), IMG.format("email-downloader"),
     "src/Features/EmailDownloader/DownloadEmailsControl.cs (OnStart, OnCancel)", UI_QA, QA_LOAD, MAN + "#email", ARCH, FDOC.format("EmailDownloader"), ""),
    (EML, "Settings (remember; no password)", "EML-8", RDF.format("email-downloader"), IMG.format("email-downloader"),
     "src/Features/EmailDownloader/EmailSettings.cs (EmailSettingsStore)",
     "tests/DigitalSecretary.UnitTests/Features/StoreTests.cs (Email_settings_round_trip)", QA_LOAD, MAN + "#email", ARCH, FDOC.format("EmailDownloader"), "Password never stored."),

    # Gmail
    (GML, "Connect & authenticate", "GML-1", RDF.format("gmail-downloader"), IMG.format("gmail-downloader"),
     "src/Features/GmailDownloader/GmailDownloader.cs (RunAsync)", NET_QA, QA_GMAIL, MAN + "#gmail", ARCH, FDOC.format("GmailDownloader"), "App password + 2-Step Verification required."),
    (GML, "Folder/label traversal (read-only)", "GML-2, GML-3", RDF.format("gmail-downloader"), IMG.format("gmail-downloader"),
     "src/Features/GmailDownloader/GmailDownloader.cs (CollectSelectableFoldersAsync)", NET_QA, QA_LOAD, MAN + "#gmail", ARCH, FDOC.format("GmailDownloader"), "EXAMINE / read-only; labels can overlap."),
    (GML, "Save .txt + .eml + mirror", "GML-4, GML-6", RDF.format("gmail-downloader"), IMG.format("gmail-downloader"),
     "src/Features/GmailDownloader/GmailDownloader.cs (SaveMessage), src/Features/GmailDownloader/GmailFileNaming.cs",
     "tests/DigitalSecretary.UnitTests/Features/GmailFileNamingTests.cs", QA_LOAD, MAN + "#gmail", ARCH, FDOC.format("GmailDownloader"), ""),
    (GML, "Attachments (incl. inline)", "GML-5", RDF.format("gmail-downloader"), IMG.format("gmail-downloader"),
     "src/Features/GmailDownloader/GmailAttachmentScanner.cs",
     "tests/DigitalSecretary.UnitTests/Features/GmailAttachmentScannerTests.cs", QA_LOAD, MAN + "#gmail", ARCH, FDOC.format("GmailDownloader"), ""),
    (GML, "Progress & cancel + errors", "GML-7", RDF.format("gmail-downloader"), IMG.format("gmail-downloader"),
     "src/Features/GmailDownloader/DownloadGmailControl.cs (OnStart, OnCancel)", UI_QA, QA_LOAD, MAN + "#gmail", ARCH, FDOC.format("GmailDownloader"), ""),
    (GML, "Settings (remember; no password)", "GML-8", RDF.format("gmail-downloader"), IMG.format("gmail-downloader"),
     "src/Features/GmailDownloader/GmailSettings.cs (GmailSettingsStore)",
     "tests/DigitalSecretary.UnitTests/Features/StoreTests.cs (Gmail_settings_round_trip)", QA_LOAD, MAN + "#gmail", ARCH, FDOC.format("GmailDownloader"), "Password never stored."),

    # Google Drive
    (GDR, "OAuth sign-in (read-only)", "GDR-1", RDF.format("google-drive-downloader"), IMG.format("google-drive-downloader"),
     "src/Features/GoogleDriveDownloader/GoogleDriveDownloader.cs (CreateServiceAsync)", NET_QA, QA_DRIVE, MAN + "#drive", ARCH, FDOC.format("GoogleDriveDownloader"), "Desktop-app OAuth client; token cached."),
    (GDR, "List & build folder tree", "GDR-2, GDR-3", RDF.format("google-drive-downloader"), IMG.format("google-drive-downloader"),
     "src/Features/GoogleDriveDownloader/GoogleDriveDownloader.cs (ListAllAsync), src/Features/GoogleDriveDownloader/DriveFileNaming.cs (ResolveFolderPath)",
     "tests/DigitalSecretary.UnitTests/Features/DriveFileNamingTests.cs", QA_LOAD, MAN + "#drive", ARCH, FDOC.format("GoogleDriveDownloader"), ""),
    (GDR, "Download regular files", "GDR-4", RDF.format("google-drive-downloader"), IMG.format("google-drive-downloader"),
     "src/Features/GoogleDriveDownloader/GoogleDriveDownloader.cs (DownloadAsync)", NET_QA, QA_LOAD, MAN + "#drive", ARCH, FDOC.format("GoogleDriveDownloader"), "Saved byte-for-byte."),
    (GDR, "Export Google docs (Office + PDF)", "GDR-5, GDR-6", RDF.format("google-drive-downloader"), IMG.format("google-drive-downloader"),
     "src/Features/GoogleDriveDownloader/GoogleExportFormats.cs, src/Features/GoogleDriveDownloader/GoogleDriveDownloader.cs (ExportAsync)",
     "tests/DigitalSecretary.UnitTests/Features/GoogleExportFormatsTests.cs", QA_LOAD, MAN + "#drive", ARCH, FDOC.format("GoogleDriveDownloader"), ""),
    (GDR, "Progress & cancel + errors", "GDR-7", RDF.format("google-drive-downloader"), IMG.format("google-drive-downloader"),
     "src/Features/GoogleDriveDownloader/DownloadDriveControl.cs (OnStart, OnCancel)", UI_QA, QA_LOAD, MAN + "#drive", ARCH, FDOC.format("GoogleDriveDownloader"), ""),
    (GDR, "Settings (remember path; token cached)", "GDR-8", RDF.format("google-drive-downloader"), IMG.format("google-drive-downloader"),
     "src/Features/GoogleDriveDownloader/DriveSettings.cs (DriveSettingsStore)",
     "tests/DigitalSecretary.UnitTests/Features/StoreTests.cs (Drive_settings_round_trip_remembers_path_not_token)", QA_LOAD, MAN + "#drive", ARCH, FDOC.format("GoogleDriveDownloader"), "Token cached separately, not in settings."),

    # Email Intelligence
    (EIN, "Ingest & parse (.eml/.txt)", "EI-A1, EI-A2, EI-A3, EI-A4", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/EmailParser.cs (ParseEml, ParseTxt), src/Features/EmailIntelligence/ArchiveScanner.cs (Filter)",
     UT_EI + "EmailParserTests.cs, " + UT_EI + "ArchiveScannerTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"),
     "MimeKit + .txt; .eml preferred over .txt sibling; offline decoding."),
    (EIN, "Clean & de-duplicate + threads", "EI-B1, EI-B2, EI-B3", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/Deduplicator.cs (KeyFor, ThreadKey)",
     UT_EI + "DeduplicatorTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"),
     "Message-Id + content hash; thread key."),
    (EIN, "Message classification", "EI-B4", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/MessageClassifier.cs (Classify)",
     UT_EI + "MessageClassifierTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"), ""),
    (EIN, "Contacts & identity resolution", "EI-C1, EI-C2, EI-C3, EI-C4", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/ContactExtractor.cs (DetectOwner), src/Features/EmailIntelligence/IdentityResolver.cs (Resolve)",
     UT_EI + "IdentityResolverTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"),
     "Merge addresses by full name; owner excluded."),
    (EIN, "Signature detail extraction", "EI-C5", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/SignatureExtractor.cs (Extract)",
     UT_EI + "SignatureExtractorTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"), ""),
    (EIN, "Contact export (vCard/CSV)", "EI-C6", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/Exporters.cs (VCardExporter, CsvExporter)",
     UT_EI + "ExportersTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"), ""),
    (EIN, "Relationship metrics & strength", "EI-D1, EI-D2, EI-D3", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/RelationshipAnalyzer.cs (Analyze)",
     UT_EI + "RelationshipAnalyzerTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"), ""),
    (EIN, "Network graph & organization", "EI-D4, EI-D5", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/NetworkGraphBuilder.cs (Build), src/Features/EmailIntelligence/IntelligencePipeline.cs (OrganizationFor)",
     UT_EI + "NetworkGraphBuilderTests.cs, " + UT_EI + "IntelligencePipelineTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"), ""),
    (EIN, "Topic extraction", "EI-E1", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/TopicExtractor.cs (GlobalTopics, AssignTopics)",
     UT_EI + "TopicExtractorTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"), ""),
    (EIN, "Tone & sentiment (lexicon)", "EI-E2", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/ToneAnalyzer.cs (Analyze, ScoreText), src/Features/EmailIntelligence/SentimentLexicon.cs",
     UT_EI + "ToneAnalyzerTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"),
     "Offline lexicon; heuristic, not AI."),
    (EIN, "Life-data extraction", "EI-F1, EI-F2, EI-F3, EI-F4", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/LifeDataExtractor.cs (Extract, Categorize, FindAmount)",
     UT_EI + "LifeDataExtractorTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"),
     "Purchases / subscriptions / travel / accounts; heuristic."),
    (EIN, "Useful-document library", "EI-F7", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/DocumentLibrary.cs (Build, Classify)",
     UT_EI + "DocumentLibraryTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"),
     "Hash-deduped attachments, typed."),
    (EIN, "Relationship-history timeline", "EI-G6", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/TimelineBuilder.cs (Build)",
     UT_EI + "TimelineBuilderTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"), ""),
    (EIN, "Portable outputs (JSON/CSV/GraphML)", "EI-H1, EI-H2, EI-H5", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/Exporters.cs (JsonExporter, GraphMlExporter)",
     UT_EI + "ExportersTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"), "No database; files only."),
    (EIN, "Unified HTML5 report", "EI-K1, EI-K2, EI-K3, EI-K4", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/HtmlReportGenerator.cs (Write)",
     UT_EI + "HtmlReportGeneratorTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"),
     "Offline; tabs; data loaded via script tag."),
    (EIN, "People search & dossier", "EI-G1, EI-G2, EI-G4", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/HtmlReportGenerator.cs (AppJs)",
     UT_EI + "HtmlReportGeneratorTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"),
     "Search, dossier, drill-through to source."),
    (EIN, "Pipeline orchestration & progress", "EI-J5, EI-I1", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/IntelligencePipeline.cs (Analyze, RunAndExport)",
     UT_EI + "IntelligencePipelineTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"),
     "Phased progress; idempotent re-run."),
    (EIN, "Append & consolidate archives", "EI-I4", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/IntelligencePipeline.cs (RunAndExport, ScanAndParse, AnalyzeCore), src/Features/EmailIntelligence/MessageStore.cs (Save, Load)",
     UT_EI + "MessageStoreTests.cs, " + UT_EI + "IntelligencePipelineTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"),
     "Persist deduped corpus; append merges + re-dedupes across archives."),
    (EIN, "Settings (folders; no secrets)", "EI-J1, EI-J3", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/EmailIntelligenceSettings.cs (EmailIntelligenceSettingsStore)",
     UT_EI + "EmailIntelligenceSettingsTests.cs", QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"), "No secrets stored."),
    (EIN, "UI (progress/cancel/open report)", "EI-J2, EI-J4", RDF.format("email-intelligence"), "-",
     "src/Features/EmailIntelligence/EmailIntelligenceControl.cs (OnStart, OnCancel, OnProgress)",
     UI_QA, QA_LOAD, UG_EI, ARCH, FDOC.format("EmailIntelligence"), "UI wires logic; covered by QA automation."),
]


def style_header(ws, ncols):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=1, column=c)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(wrap_text=True, vertical="center", horizontal="left")
        cell.border = BORDER
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(ncols)}1"
    ws.row_dimensions[1].height = 30


def style_body(ws, nrows, ncols):
    for r in range(2, nrows + 1):
        for c in range(1, ncols + 1):
            cell = ws.cell(row=r, column=c)
            cell.font = BODY_FONT
            cell.alignment = WRAP_TOP
            cell.border = BORDER


def build_requirements(path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Requirements"
    ws.append(REQ_HEADERS)
    for row in REQUIREMENTS:
        ws.append(list(row))
    widths = [9, 11, 18, 18, 9, 8, 30, 48, 38, 38, 34]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w
    style_header(ws, len(REQ_HEADERS))
    style_body(ws, len(REQUIREMENTS) + 1, len(REQ_HEADERS))
    ws["A1"].comment = Comment(BANNER, "build_excel_docs")

    # ReadMe / import sheet
    rm = wb.create_sheet("ReadMe")
    notes = [
        ["DigitalSecretary - Requirements"],
        [BANNER],
        ["Purpose", "Flat list of all requirements (App, Features, Sub-features, NFRs)."],
        ["Detailed source", "docs/requirements/REQUIREMENTS.md and docs/requirements/features/*.md"],
        ["Traceability", "docs/traceability/DigitalSecretary-Traceability-Matrix.xlsx"],
        ["Regenerate", "python tools/docgen/build_excel_docs.py"],
        [""],
        ["JIRA import tips"],
        ["1", "Use 'Req ID' as a label or a custom field; 'Issue Type' maps to Story/NFR."],
        ["2", "'Feature (Epic)' is the Epic Link; 'Summary' is the issue summary."],
        ["3", "Map Description, User Story, Acceptance Criteria to your fields."],
    ]
    for row in notes:
        rm.append(row)
    rm["A1"].font = Font(name=FONT, bold=True, size=14)
    rm["A2"].font = BANNER_FONT
    rm["A8"].font = Font(name=FONT, bold=True, size=10)
    rm.column_dimensions["A"].width = 18
    rm.column_dimensions["B"].width = 80
    for r in range(2, len(notes) + 1):
        for c in (1, 2):
            if r in (2, 8):
                continue
            rm.cell(row=r, column=c).font = BODY_FONT
            rm.cell(row=r, column=c).alignment = WRAP_TOP
    wb.save(path)


def build_traceability(path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Traceability Matrix"
    ws.append(TRACE_HEADERS)
    cov_col = 12  # L
    for i, row in enumerate(TRACE, start=2):
        # row has 12 values: cols A..K then Notes(M). Insert coverage formula at L.
        a_to_k = list(row[:11])
        notes = row[11]
        for c, val in enumerate(a_to_k, start=1):
            ws.cell(row=i, column=c, value=val)
        # Coverage: required artifacts = Req Doc(D), Code(F), Unit Test(G), QA(H), Manual(I), Code Doc(K)
        ws.cell(row=i, column=cov_col,
                value=f'=IF(COUNTA(D{i},F{i},G{i},H{i},I{i},K{i})=6,"Complete","Gap - fill artifacts")')
        ws.cell(row=i, column=13, value=notes)

    widths = [16, 26, 16, 30, 26, 40, 40, 40, 26, 22, 26, 16, 24]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w
    style_header(ws, len(TRACE_HEADERS))
    style_body(ws, len(TRACE) + 1, len(TRACE_HEADERS))
    ws["A1"].comment = Comment(BANNER, "build_excel_docs")

    # Conditional formatting on Coverage column
    last = len(TRACE) + 1
    rng = f"L2:L{last}"
    green = PatternFill("solid", fgColor="C6EFCE")
    red = PatternFill("solid", fgColor="FFC7CE")
    ws.conditional_formatting.add(rng, FormulaRule(formula=['ISNUMBER(SEARCH("Gap",L2))'], fill=red))
    ws.conditional_formatting.add(rng, FormulaRule(formula=['$L2="Complete"'], fill=green))

    # Legend sheet
    lg = wb.create_sheet("Legend")
    rows = [
        ["DigitalSecretary - Bi-directional Traceability Matrix"],
        [BANNER],
        ["How to use", "Trace any artifact to any other across a row. Filter by any column (header arrows)."],
        ["Coverage", "Auto-flags 'Complete' when Req Doc, Code, Unit Test, QA, User Manual and Code Doc are all present; otherwise 'Gap'."],
        ["'n/a (UI/network)'", "UI/network behaviour is validated by QA automation + manual runs, not unit tests (by design)."],
        ["Mock / Screen", "Reference screenshot in the User Manual images (design mockups would go here if produced)."],
        ["Regenerate", "python tools/docgen/build_excel_docs.py"],
        ["Requirements list", "docs/requirements/DigitalSecretary-Requirements.xlsx"],
    ]
    for row in rows:
        lg.append(row)
    lg["A1"].font = Font(name=FONT, bold=True, size=14)
    lg["A2"].font = BANNER_FONT
    lg.column_dimensions["A"].width = 22
    lg.column_dimensions["B"].width = 90
    for r in range(3, len(rows) + 1):
        for c in (1, 2):
            lg.cell(row=r, column=c).font = BODY_FONT
            lg.cell(row=r, column=c).alignment = WRAP_TOP
    wb.save(path)


def main():
    req_path = ROOT / "docs" / "requirements" / "DigitalSecretary-Requirements.xlsx"
    trace_path = ROOT / "docs" / "traceability" / "DigitalSecretary-Traceability-Matrix.xlsx"
    req_path.parent.mkdir(parents=True, exist_ok=True)
    trace_path.parent.mkdir(parents=True, exist_ok=True)
    build_requirements(req_path)
    build_traceability(trace_path)
    print(f"Requirements:  {req_path}  ({len(REQUIREMENTS)} requirements)")
    print(f"Traceability:  {trace_path}  ({len(TRACE)} rows)")


if __name__ == "__main__":
    main()
