"""Generate the DigitalSecretary DevEconomics workbook (per-activity cost + time ledger).

Single source of truth = this script's data tables. Captures EVERY activity Claude performs to
build a feature, classified by cost bucket, with token/cost and time, plus a per-feature summary
that tracks ESTIMATE vs ACTUAL and a trend chart.

Cost buckets:
  A = LLM tokens (the only metered cost)   B = local compute ($0)   C = remote/network ($0)

Outputs:
  docs/deveconomics/DigitalSecretary-DevEconomics.xlsx

Run:  python tools/docgen/build_deveconomics.py

Notes on truth: token/cost for LLM rows are ESTIMATES (the model can't read its own meter). Local
times are MEASURED from command output where captured, else estimated. Replace per-feature ACTUAL
cost with the figure from `/cost` (Claude Code) or the Anthropic Console, then re-run.
"""
from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.comments import Comment
from openpyxl.chart import BarChart, Reference

BANNER = ("AUTO-GENERATED by tools/docgen/build_deveconomics.py - do NOT edit this workbook by hand. "
          "Edit the script's data tables and run: python tools/docgen/build_deveconomics.py")
ROOT = Path(__file__).resolve().parents[2]
FONT = "Arial"
HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
HEADER_FONT = Font(name=FONT, bold=True, color="FFFFFF", size=10)
BODY_FONT = Font(name=FONT, size=10)
BANNER_FONT = Font(name=FONT, bold=True, color="C00000", size=10)
WRAP_TOP = Alignment(wrap_text=True, vertical="top")
THIN = Side(style="thin", color="D9D9D9")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
A_FILL = PatternFill("solid", fgColor="FCE4D6")  # LLM (cost) - warm
B_FILL = PatternFill("solid", fgColor="E2EFDA")  # local ($0) - green
C_FILL = PatternFill("solid", fgColor="DDEBF7")  # remote ($0) - blue

# Opus 4.8 rate card (USD per 1M tokens) - see docs/DEVECONOMICS.md.
RATE = {"in": 5.0, "out": 25.0, "cache_read": 0.50, "cache_write": 6.25}

# --------------------------------------------------------------------------- #
# 1. ACTIVITY LOG - one row per activity Claude performed.
#    (Phase, Activity, Bucket, Tool/Method, LLM?, EstTokens, EstCostUSD, TimeMin, TimeBasis, Notes)
#    Bucket: "A" LLM tokens | "B" local compute | "C" remote | "B+C" local that pulls from network.
# --------------------------------------------------------------------------- #
FEATURE = "Gmail + Google Drive downloaders"
FEATURE_DATE = "2026-06-22"
MODEL = "Opus 4.8"
PRODUCTION_KLOC = 1.03  # Gmail 521 + Drive 512 lines of production C#

ACTIVITIES = [
    ("Explore", "Read CLAUDE.md; locate solution & memory", "A", "Read/Glob", "Yes", 4000, 0.05, 1.5, "estimate", "orient"),
    ("Explore", "Study EmailDownloader (control, IMAP, settings, helpers)", "A", "Read", "Yes", 12000, 0.12, 3.0, "estimate", "model to clone"),
    ("Explore", "Read contract, ADDING_A_FEATURE, Directory.Build.props", "A", "Read", "Yes", 6000, 0.07, 1.5, "estimate", ""),
    ("Explore", "Read unit + QA tests and QA harness", "A", "Read", "Yes", 7000, 0.08, 1.5, "estimate", ""),
    ("Explore", "Read build.ps1, docgen scripts, check_docs", "A", "Read", "Yes", 14000, 0.14, 3.0, "estimate", "quality gates"),
    ("Explore", "Read requirements/user-guide/journal/manual template/DocShots", "A", "Read", "Yes", 13000, 0.13, 3.0, "estimate", "docs pipeline"),
    ("Decide", "Ask 3 scoping questions (IMAP vs API, OAuth, export fmt)", "A", "AskUserQuestion", "Yes", 2000, 0.06, 1.0, "estimate", "blocking decisions"),
    ("Setup", "Verify toolchain (dotnet/python/nuget/git/openpyxl)", "B", "PowerShell", "No", 0, 0.0, 0.2, "measured", ""),

    ("Build Gmail", "Author 9 Gmail files (module, control, IMAP, naming, scanner, settings, manifest, FEATURE)", "A", "Write", "Yes", 14000, 0.45, 6.0, "estimate", "521 LOC"),
    ("Build Gmail", "Add project to solution + unit-test reference", "B", "dotnet sln/add", "No", 0, 0.0, 0.2, "measured", ""),
    ("Build Gmail", "Compile Gmail feature (0 warnings)", "B", "dotnet build", "No", 0, 0.0, 0.14, "measured", "8.4s"),

    ("Build Drive", "Author pure logic (export formats, file naming, settings)", "A", "Write", "Yes", 6000, 0.18, 3.0, "estimate", "testable, no Google dep"),
    ("Build Drive", "Author csproj / manifest / module", "A", "Write", "Yes", 2000, 0.06, 1.0, "estimate", ""),
    ("Build Drive", "Add Google.Apis.Drive.v3 + restore", "B+C", "dotnet add package", "No", 0, 0.0, 0.10, "measured", "NuGet download 5.9s"),
    ("Build Drive", "Author OAuth + Drive API downloader + control + FEATURE", "A", "Write", "Yes", 9000, 0.40, 4.0, "estimate", "512 LOC"),
    ("Build Drive", "Simplify download helper", "A", "Edit", "Yes", 1500, 0.04, 0.5, "estimate", ""),
    ("Build Drive", "Add to solution + unit-test reference", "B", "dotnet sln/add", "No", 0, 0.0, 0.2, "measured", ""),
    ("Build Drive", "Compile Drive (2 analyzer warnings)", "B", "dotnet build", "No", 0, 0.0, 0.10, "measured", "6.3s"),
    ("Build Drive", "Fix CA1859 + CA2016 warnings", "A", "Edit", "Yes", 1500, 0.04, 0.5, "estimate", ""),
    ("Build Drive", "Recompile Drive (0 warnings)", "B", "dotnet build", "No", 0, 0.0, 0.04, "measured", "2.5s"),

    ("Tests", "Author 4 unit-test files (Gmail + Drive logic)", "A", "Write", "Yes", 6000, 0.20, 3.0, "estimate", "233 LOC"),
    ("Tests", "Add settings round-trips + QA private-dependency tests", "A", "Edit", "Yes", 3000, 0.10, 1.5, "estimate", ""),
    ("Tests", "Build full solution", "B", "dotnet build", "No", 0, 0.0, 0.21, "measured", "12.5s, 0 warn"),
    ("Tests", "Run unit tests", "B", "dotnet test", "No", 0, 0.0, 0.07, "measured", "85 pass, 4s"),
    ("Tests", "Run QA automation", "B", "dotnet test", "No", 0, 0.0, 0.02, "measured", "17 pass, 1s"),

    ("Docs", "Author requirement + user-guide docs (4)", "A", "Write", "Yes", 6000, 0.20, 3.0, "estimate", ""),
    ("Docs", "Update REQUIREMENTS / USER_GUIDE indexes", "A", "Edit", "Yes", 1500, 0.05, 1.0, "estimate", ""),
    ("Docgen", "Edit build_excel_docs.py + check_docs.py (GML/GDR rows + ID regex)", "A", "Edit", "Yes", 5000, 0.14, 2.5, "estimate", ""),
    ("Docgen", "Regenerate requirements + traceability xlsx", "B", "python", "No", 0, 0.0, 0.05, "measured", "56 req, 37 trace"),
    ("Docgen", "Run docs consistency checker", "B", "python check_docs", "No", 0, 0.0, 0.05, "measured", "caught 24 expected"),

    ("Manual", "Edit manual template (TOC + 2 sections) + DocShots seed", "A", "Edit", "Yes", 4000, 0.12, 2.5, "estimate", ""),
    ("Manual", "Generate screenshots", "B", "dotnet run DocShots", "No", 0, 0.0, 0.25, "measured", "8 PNGs"),
    ("Manual", "Build single-file HTML manual", "B", "build-user-manual.ps1", "No", 0, 0.0, 0.03, "measured", "192KB, clean"),
    ("Manual", "Re-run consistency checker", "B", "python check_docs", "No", 0, 0.0, 0.05, "measured", "0 errors"),

    ("Gate", "Append DEVELOPMENT_JOURNAL phase", "A", "Edit", "Yes", 2000, 0.06, 1.0, "estimate", ""),
    ("Gate", "Full quality gate", "B", "build.ps1 -All", "No", 0, 0.0, 0.7, "measured", "PASS, 72.9% cov"),
    ("Gate", "Fix coverage.runsettings exclusions", "A", "Edit", "Yes", 1500, 0.04, 0.5, "estimate", "exclude network classes"),
    ("Gate", "Re-run gate with -MinCoverage 80", "B", "build.ps1 -All", "No", 0, 0.0, 0.7, "measured", "PASS, 89.9%"),
    ("Review", "Cleanliness scan (mojibake) + git status", "B", "Grep/git", "No", 0, 0.0, 0.1, "measured", "0 mojibake"),
    ("Commit", "Commit + pre-commit gate", "B", "git commit", "No", 0, 0.0, 0.3, "measured", "1df66a4"),
]

# Shared session overhead not attributable to one activity: the growing transcript re-sent each
# turn, served mostly from cache (~0.1x input). Estimated; reconcile the total against /cost.
CONTEXT_OVERHEAD_USD = 2.77

ACT_HEADERS = ["#", "Phase", "Activity", "Bucket", "Tool / Method", "LLM?",
               "Est. Tokens", "Est. Cost (USD)", "Time (min)", "Time Basis", "Notes"]


def bucket_label(code):
    return {"A": "A - LLM tokens", "B": "B - Local ($0)", "C": "C - Remote ($0)",
            "B+C": "B+C - Local+net ($0)"}[code]


def bucket_fill(code):
    return A_FILL if code == "A" else (C_FILL if code == "C" else B_FILL)


def style_header(ws, ncols):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=1, column=c)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(wrap_text=True, vertical="center", horizontal="left")
        cell.border = BORDER
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(ncols)}1"
    ws.row_dimensions[1].height = 28


def build_activity_log(ws):
    ws.title = "Activity Log"
    ws.append(ACT_HEADERS)
    for i, (phase, act, bucket, tool, llm, tok, cost, tmin, basis, notes) in enumerate(ACTIVITIES, start=1):
        ws.append([i, phase, act, bucket_label(bucket), tool, llm,
                   tok if tok else None, round(cost, 2), tmin, basis, notes])
        row = i + 1
        fill = bucket_fill(bucket)
        ws.cell(row=row, column=4).fill = fill
        ws.cell(row=row, column=8).number_format = '$#,##0.00'
        ws.cell(row=row, column=9).number_format = '0.00'

    total_row = len(ACTIVITIES) + 2
    ws.cell(row=total_row, column=3, value="TOTAL (direct, sum of activities)").font = Font(name=FONT, bold=True, size=10)
    ws.cell(row=total_row, column=7, value=f"=SUM(G2:G{total_row-1})")
    ws.cell(row=total_row, column=8, value=f"=SUM(H2:H{total_row-1})").number_format = '$#,##0.00'
    ws.cell(row=total_row, column=9, value=f"=SUM(I2:I{total_row-1})").number_format = '0.00'
    for c in (7, 8, 9):
        ws.cell(row=total_row, column=c).font = Font(name=FONT, bold=True, size=10)

    widths = [4, 12, 52, 20, 20, 6, 11, 13, 10, 11, 26]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w
    style_header(ws, len(ACT_HEADERS))
    for r in range(2, total_row + 1):
        for c in range(1, len(ACT_HEADERS) + 1):
            cell = ws.cell(row=r, column=c)
            if cell.font.bold:
                continue
            cell.font = BODY_FONT
            cell.alignment = WRAP_TOP
            cell.border = BORDER
    ws["A1"].comment = Comment(BANNER, "build_deveconomics")


def feature_rollup():
    a = [x for x in ACTIVITIES if x[2] == "A"]
    bc = [x for x in ACTIVITIES if x[2] != "A"]
    direct_cost = round(sum(x[6] for x in ACTIVITIES), 2)
    local_time = round(sum(x[7] for x in ACTIVITIES if x[2] != "A"), 2)
    total_time = round(sum(x[7] for x in ACTIVITIES), 2)
    total_est = round(direct_cost + CONTEXT_OVERHEAD_USD, 2)
    return {
        "activities": len(ACTIVITIES), "a": len(a), "bc": len(bc),
        "direct_cost": direct_cost, "overhead": CONTEXT_OVERHEAD_USD, "total_est": total_est,
        "local_time": local_time, "total_time": total_time,
    }


SUM_HEADERS = ["Feature", "Date", "Model", "Activities", "LLM (A)", "Local/Remote (B/C)",
               "Direct LLM cost EST ($)", "Context/cache overhead EST ($)", "Total cost EST ($)",
               "Total cost ACTUAL ($)", "Cost variance ($)", "Local compute time (min)",
               "Total time EST (min)", "Total time ACTUAL (min)", "Prod. KLOC", "$/KLOC EST", "Notes"]


def build_feature_summary(ws, roll):
    ws.title = "Feature Summary"
    ws.append(SUM_HEADERS)
    # ACTUAL columns (J, N) left blank until reconciled with /cost.
    ws.append([
        FEATURE, FEATURE_DATE, MODEL, roll["activities"], roll["a"], roll["bc"],
        roll["direct_cost"], roll["overhead"], roll["total_est"],
        None,                                   # J: Total cost ACTUAL (run /cost)
        '=IF(ISNUMBER(J2),J2-I2,"pending /cost")',  # K: variance
        roll["local_time"], roll["total_time"],
        None,                                   # N: Total time ACTUAL
        PRODUCTION_KLOC, round(roll["total_est"] / PRODUCTION_KLOC, 2),
        "Estimate; reconcile ACTUAL via /cost. Excludes the DevEconomics report + cost analysis.",
    ])
    for col in ("G", "H", "I", "J", "K", "P"):
        ws[f"{col}2"].number_format = '$#,##0.00'
    widths = [30, 12, 9, 10, 8, 14, 16, 18, 14, 16, 14, 14, 14, 16, 10, 11, 40]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w
    style_header(ws, len(SUM_HEADERS))
    for r in range(2, ws.max_row + 1):
        for c in range(1, len(SUM_HEADERS) + 1):
            cell = ws.cell(row=r, column=c)
            cell.font = BODY_FONT
            cell.alignment = WRAP_TOP
            cell.border = BORDER
    ws["A1"].comment = Comment(BANNER, "build_deveconomics")
    return ws


def build_trend(wb, summary_ws):
    ws = wb.create_sheet("Trend")
    ws["A1"] = "DevEconomics trend - estimate vs actual per feature"
    ws["A1"].font = Font(name=FONT, bold=True, size=13)
    ws["A2"] = BANNER
    ws["A2"].font = BANNER_FONT
    ws["A4"] = ("As features accumulate, each row in 'Feature Summary' adds a point here. The chart "
                "compares estimated vs actual cost so the estimate error trends toward zero. Fill the "
                "ACTUAL columns from /cost after each feature, then re-run the generator.")
    ws["A4"].alignment = WRAP_TOP
    ws.column_dimensions["A"].width = 100

    last = summary_ws.max_row  # data rows in Feature Summary
    # Cost chart: EST (col I) vs ACTUAL (col J), categories = Feature (col A).
    cost_chart = BarChart()
    cost_chart.type = "col"
    cost_chart.title = "Cost per feature: EST vs ACTUAL ($)"
    cost_chart.y_axis.title = "USD"
    cost_chart.x_axis.title = "Feature"
    cost_data = Reference(summary_ws, min_col=9, max_col=10, min_row=1, max_row=last)
    cost_cats = Reference(summary_ws, min_col=1, max_col=1, min_row=2, max_row=last)
    cost_chart.add_data(cost_data, titles_from_data=True)
    cost_chart.set_categories(cost_cats)
    cost_chart.height = 8
    cost_chart.width = 16
    ws.add_chart(cost_chart, "A7")

    # Time chart: EST (col M) vs ACTUAL (col N).
    time_chart = BarChart()
    time_chart.type = "col"
    time_chart.title = "Time per feature: EST vs ACTUAL (min)"
    time_chart.y_axis.title = "minutes"
    time_chart.x_axis.title = "Feature"
    time_data = Reference(summary_ws, min_col=13, max_col=14, min_row=1, max_row=last)
    time_chart.add_data(time_data, titles_from_data=True)
    time_chart.set_categories(cost_cats)
    time_chart.height = 8
    time_chart.width = 16
    ws.add_chart(time_chart, "A24")


def build_readme(wb, roll):
    ws = wb.create_sheet("ReadMe")
    rows = [
        ["DigitalSecretary - DevEconomics workbook"],
        [BANNER],
        ["Purpose", "Per-activity cost + time ledger for codeless development, with per-feature "
                    "estimate-vs-actual tracking and a trend chart."],
        ["Cost buckets", "A = LLM tokens (the only metered cost); B = local compute ($0 tokens); "
                         "C = remote/network ($0 tokens)."],
        ["Rate card (Opus 4.8, $/1M tok)", f"input {RATE['in']}, output {RATE['out']}, "
                                           f"cache-read {RATE['cache_read']}, cache-write {RATE['cache_write']}."],
        ["Truth & estimates", "Token/cost for LLM rows are ESTIMATES (the model can't read its own "
                              "meter). Local times are MEASURED from command output where captured. "
                              "Per-feature ACTUAL cost comes from /cost (Claude Code) or the Anthropic "
                              "Console - fill columns J/N in Feature Summary, then re-run."],
        ["This run", f"{roll['activities']} activities ({roll['a']} LLM / {roll['bc']} local|remote); "
                     f"~${roll['total_est']} est total; ~{roll['total_time']} min est "
                     f"(of which ~{roll['local_time']} min measured local compute)."],
        ["Regenerate", "python tools/docgen/build_deveconomics.py"],
        ["Companion", "docs/DEVECONOMICS.md (narrative + improvement levers); "
                      "docs/DEVELOPMENT_JOURNAL.md (what/why)."],
    ]
    for row in rows:
        ws.append(row)
    ws["A1"].font = Font(name=FONT, bold=True, size=14)
    ws["A2"].font = BANNER_FONT
    ws.column_dimensions["A"].width = 32
    ws.column_dimensions["B"].width = 95
    for r in range(3, len(rows) + 1):
        for c in (1, 2):
            ws.cell(row=r, column=c).font = BODY_FONT
            ws.cell(row=r, column=c).alignment = WRAP_TOP


def main():
    roll = feature_rollup()
    wb = Workbook()
    build_activity_log(wb.active)
    summary_ws = build_feature_summary(wb.create_sheet("Feature Summary"), roll)
    build_trend(wb, summary_ws)
    build_readme(wb, roll)

    out = ROOT / "docs" / "deveconomics" / "DigitalSecretary-DevEconomics.xlsx"
    out.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out)
    print(f"DevEconomics: {out}")
    print(f"  {roll['activities']} activities | direct ${roll['direct_cost']} + overhead "
          f"${roll['overhead']} = ${roll['total_est']} est | {roll['total_time']} min est "
          f"({roll['local_time']} min local measured)")


if __name__ == "__main__":
    main()
